name: ASP.NET Lambda Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      AWS_IAM_ROLE_ARN: ${{secrets.AWS_IAM_ROLE_ARN}}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    
    - name: AWS CLI
      run: dotnet tool install -g Amazon.Lambda.Tools
      
    - name: Build and Publish
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Lambda
      run:  dotnet lambda deploy-function --region ${{secrets.AWS_DEFAULT_REGION}} --function-runtime dotnet6 --function-name mythic-empire-backend-service --function-role ${{secrets.AWS_IAM_ROLE_ARN}} 